### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by Aratramba** [github/combobox-nav#23]
Hi, I noticed the [example](https://github.github.io/combobox-nav/examples/) isn't working. When I focus the input field this error message pops up in the console:

```
Uncaught TypeError: comboboxNav.stop is not a function
    at HTMLInputElement.toggleList ((index):33)
```

This happens on Chrome/Firefox/Opera/Safari OSX.

![image](https://user-images.githubusercontent.com/580312/80450076-02ac6500-8921-11ea-9eed-6fd497c8e492.png)

**Comment by koddsson** [comment]
Seems to be because we haven't published a new version since we changed the API in https://github.com/github/combobox-nav/pull/21. This should be fixed after we merge #22 and publish.

cc/ @muan

**Comment by Aratramba** [comment]
I see, https://html-is.glitch.me/github/combobox-nav-22.html seems to work just fine. You might for now just put that link up in the Github description. 

![image](https://user-images.githubusercontent.com/580312/80470642-95113080-8942-11ea-8dc3-0200e1bf334a.png)

**Comment by muan** [comment]
Fixed in https://github.com/github/combobox-nav/commit/24bf19476fb4e255cb598cc1e28e7ed83dd4ca96.

I added the old demo back and linked to it: https://github.github.io/combobox-nav/examples/index-v1.0.2.html
