### ISSUE TITLE
Ctrl key clears selection before Ctrl+N or Ctrl+P keycombo can be used

### ISSUE THREAD

**Issue by T-Hugs** [github/combobox-nav#25]
In https://github.com/github/combobox-nav/blob/master/src/index.ts#L130, a `keydown` event for the Ctrl key will fall to the `default` case, clearing the selection. This always makes Ctrl+P and Ctrl+N start at the beginning.

I don't think the selection should be cleared in a `keydown` handler. Perhaps an `input` handler would be more appropriate for that.

**Comment by muan** [comment]
Nice catch. Thanks!
